server:
  port: 8189
  servlet:
    context-path: /market
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sec
    username: postgres
    password: ${dbPassword}
  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: false
  jackson:
    serialization:
      indent_output: true

#      -Dspring.profiles.active=thymeleaf