//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.02 at 11:47:57 PM MSK 
//


package ru.zakharova.elena.market.entities.dtos;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = {
    "id",
    "title",
    "price",
    "categoriesDTOs"
})
public class ProductDTO {

    private Long id;

    @XmlElement(required = true)
    @Size(min = 4, max = 255)
    private String title;

    @XmlElement(required = true)
    private BigDecimal price;

    @XmlElement(required = true)
    private List<CategoryDTO> categoriesDTOs;

    public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    public List<CategoryDTO> getCategoriesDTOs() {
        if (categoriesDTOs == null) {
            categoriesDTOs = new ArrayList<>();
        }
        return this.categoriesDTOs;
    }

}
