//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.22 at 03:11:11 PM MSK 
//


package ru.zakharova.elena.market.utils.ws;

import org.springframework.stereotype.Component;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "titlePart"
})
@XmlRootElement(name = "getProductRequest")
@Component
public class GetProductRequest {

    @XmlElement(required = true)
    protected String titlePart;

    public String getTitlePart() {
        return titlePart;
    }

    public void setTitlePart(String value) {
        this.titlePart = value;
    }

}
