//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.22 at 03:11:11 PM MSK 
//


package ru.zakharova.elena.market.utils.ws;

import ru.zakharova.elena.market.entities.dtos.CategoryDTO;
import ru.zakharova.elena.market.entities.dtos.ProductDTO;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zakharova-elena.spring.ws.products
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductRequest }
     *
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link GetProductResponse }
     *
     */
    public GetProductResponse createGetProductResponse() {
        return new GetProductResponse();
    }

    /**
     * Create an instance of {@link ProductDTO }
     *
     */
    public ProductDTO createProduct() {
        return new ProductDTO();
    }

    /**
     * Create an instance of {@link CategoryDTO }
     *
     */
    public CategoryDTO createCategory() {
        return new CategoryDTO();
    }

}
