//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.22 at 03:11:11 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zakharova-elena.com/spring/ws/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.zakharova.elena.market.utils.ws;
